---
edx_platform_repo: "%%PLATFORM_REPO%%"
edx_platform_version: "%%PLATFORM_VERSION%%"
edx_ansible_source_repo: "%%CONFIGURATION_REPO%%"
configuration_version: "%%CONFIGURATION_VERSION%%"
azure_media_version: "%%AZURE_MEDIA_VERSION%%"
kitchen_sink_course_version: "%%KITCHEN_SINK_COURSE_VERSION%%"
certs_version: "%%EDX_VERSION%%"
forum_source_repo: "https://github.com/Microsoft/cs_comments_service"
forum_version: "%%FORUM_VERSION%%"
xqueue_version: "%%EDX_VERSION%%"
demo_version: "%%EDX_VERSION%%"
ECOMMERCE_VERSION: "%%EDX_VERSION%%"
ECOMMERCE_WORKER_VERSION: "%%EDX_VERSION%%"
PROGRAMS_VERSION: "%%EDX_VERSION%%"
NOTIFIER_VERSION: "%%EDX_VERSION%%"
